### ISSUE TITLE
Encoding and decoding of c strings is affected by locale settings

### ISSUE THREAD

**Issue by h-3-0** [jakubfijalkowski/hsass#11]
The functions `peekCString` etc. used for communication with libsass determine the encoding used in the c string from the environment's locale settings. This is similar to what [beware of readFile](https://www.snoyman.com/blog/2016/12/beware-of-readfile) warns of, but I think it's especially applicable here because we know that libsass accepts and produces only UTF-8. Locale settings should not be relevant.

I discovered this by using Stack's Nix integration, which clobbers most environment variables. As an example, if you use hsass in an environment where `LC_CTYPE=POSIX`, non-ASCII characters get dropped.

It should be possible to replace `peekCString` etc. with the corresponding functions from `GHC.IO`, which would allow for specifying the encoding. One tricky issue is what to do with filepaths, since I suppose their encoding should be determined by the environment. There is [getFilesystemEncoding](https://www.stackage.org/haddock/lts-10.5/base-4.10.1.0/GHC-IO-Encoding.html#v:getFileSystemEncoding) — which comes with a warning that it shouldn't be used on Windows — but without a better understanding and a reproducible test case I'm inclined to leave filepaths alone.

**Comment by jakubfijalkowski** [comment]
Ah, I love this environment dependent behaviors. I'll look into it a little bit more on the weekend (or on the next weekend), because it might also affect `hlibsass` (which I plan to update sometime soon).

**Comment by jakubfijalkowski** [comment]
Ok, with commit 901d781 I've switched from `newCString`/`peekCString`/`withCString` to UTF-8 equivalents. It seems that everything works as expected, except the paths - I've ignored the fact, that file system might have different encoding. On Windows,
 [Libsass](https://github.com/sass/libsass/blob/3af837c4e6053487186cfcf564a990ff11e4e356/src/file.cpp#L431-L453) assumes that the path string is in UTF-8, so that's not a problem (we can encode it just like any other string), but it [does nothing](https://github.com/sass/libsass/blob/3af837c4e6053487186cfcf564a990ff11e4e356/src/file.cpp#L456) on non-Windows platforms. Will investigate more (i.e. test on non-UTF-8 filesystems).

Leaving the issue open, as the filesystem case is still not resolved completely.

**Comment by jakubfijalkowski** [comment]
Okay, I've decided to ignore the filesystem encoding problem (and finally got understanding how it works on Linux). Most systems use UTF-8 for paths encoding, and as far as I know - it really depends which `libc` is used (and app can change it freely).

If it will be a problem, I'll adapt `hsass` to use `getFilesystemEncoding`, but as for now I'm leaving it as is.
