### ISSUE TITLE
Unable to run compileFile from GHCi on OS X

### ISSUE THREAD

**Issue by iand675** [jakubfijalkowski/hsass#2]
When I load GHCi, and try to use hsass, I get an error:

``` haskell
λ :m + Text.Sass
λ compileFile "./stylesheets/default.scss" (def { sassIncludePaths = Just ["stylesheets/"] }) :: IO (Either SassError String)
<interactive>:
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/ian/Code/iankduncan/.cabal-sandbox/lib/x86_64-osx-ghc-7.10.1/hlibs_HR5edJE2XT1IuQkKGmjCv9/libsass.a: unknown symbol `___dso_handle'
ghc: unable to load package `hlibsass-0.1.2.0'
```

Do you have any idea what's wrong?

**Comment by jakubfijalkowski** [comment]
I know that this problem exists. Unfortunately, I have no idea why it occurs. I will try to investigate this problem once more during the weekend, maybe this time I will find something more.

**Comment by jakubfijalkowski** [comment]
I think I was able to bypass the problem. You _just_ have to use [hLibsass](https://github.com/jakubfijalkowski/hlibsass) that is linked against shared version of `libsass`. I've just introduced this feature in v0.1.3.0 of hLibsass (with the `sharedLibsass` flag).

Because Cabal does not allow to specify flags in the `*.cabal` file, you have to install hLibsass manually with:

```
cabal install hlibsass -f sharedLibsass
```

This should install correct version of hLibsass. If `ghci`/`cabal repl` complains about the lack of `libsass.so`, make `LD_LIBRARY_PATH` point to hlibsass' install location (you may use [this script](https://github.com/jakubfijalkowski/hlibsass/blob/master/tools/libpath.sh) to extract it from cabal).

By the way - you may use `StringResult` instead of `IO (Either SassError String)`.

**Comment by jakubfijalkowski** [comment]
Ok, I think that my solution has solved the problem and there were no more comments, I close this issue.
